name: polly_flutter_example
description: Example app demonstrating polly_flutter resilient widgets.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  polly_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
